package com.clover.labs.json;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.09 at 01:51:51 PM CEST
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomerRelationSignatory complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CustomerRelationSignatory"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rimNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="middleInitial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="relationshipId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="relationship" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="portfolio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="signor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cosignorLiability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerRelationSignatory", propOrder = {
        "rimNumber",
        "firstName",
        "middleInitial",
        "lastName",
        "relationshipId",
        "relationship",
        "status",
        "portfolio",
        "signor",
        "cosignorLiability"
})
public class CustomerRelationSignatory {

    protected String rimNumber;
    protected String firstName;
    protected String middleInitial;
    protected String lastName;
    protected String relationshipId;
    protected String relationship;
    protected String status;
    protected String portfolio;
    protected String signor;
    protected String cosignorLiability;

    public CustomerRelationSignatory() {

    }

    public CustomerRelationSignatory(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    /**
     * Gets the value of the rimNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRimNumber() {
        return rimNumber;
    }

    /**
     * Sets the value of the rimNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRimNumber(String value) {
        this.rimNumber = value;
    }

    /**
     * Gets the value of the firstName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleInitial property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMiddleInitial() {
        return middleInitial;
    }

    /**
     * Sets the value of the middleInitial property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMiddleInitial(String value) {
        this.middleInitial = value;
    }

    /**
     * Gets the value of the lastName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the relationshipId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRelationshipId() {
        return relationshipId;
    }

    /**
     * Sets the value of the relationshipId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRelationshipId(String value) {
        this.relationshipId = value;
    }

    /**
     * Gets the value of the relationship property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * Sets the value of the relationship property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRelationship(String value) {
        this.relationship = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the portfolio property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPortfolio() {
        return portfolio;
    }

    /**
     * Sets the value of the portfolio property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPortfolio(String value) {
        this.portfolio = value;
    }

    /**
     * Gets the value of the signor property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSignor() {
        return signor;
    }

    /**
     * Sets the value of the signor property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSignor(String value) {
        this.signor = value;
    }

    /**
     * Gets the value of the cosignorLiability property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCosignorLiability() {
        return cosignorLiability;
    }

    /**
     * Sets the value of the cosignorLiability property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCosignorLiability(String value) {
        this.cosignorLiability = value;
    }

}
